### ISSUE TITLE
Consulta rango bajo shield arduino

### ISSUE THREAD

**Issue by sabas1080** [ElectronicCats/CatWANShield#1]
Buen dia como le comente por llamada tengo problema con el rango de transmisión de mi shield para arduino. Envio fotos de mi conexion, las antenas que utilizo y la potencia.

Las conexiones que tiene el arduino son solo 4 botones de input y la pantalla lcd. 

La potencia que tengo es a una distancia de unos 20cm.

Estoy usando el codigo del repositorio de LoRa, LoRaDuplex.

De antemanos agradezco la ayuda 
![WhatsApp Image 2019-11-05 at 9 36 02 AM](https://user-images.githubusercontent.com/2874292/68228129-83b22180-ffba-11e9-8d8b-450bee0cf151.jpeg)
![WhatsApp Image 2019-11-05 at 9 34 52 AM (1)](https://user-images.githubusercontent.com/2874292/68228132-84e34e80-ffba-11e9-9d2f-0b0ce8aa877f.jpeg)
![WhatsApp Image 2019-11-05 at 9 34 51 AM](https://user-images.githubusercontent.com/2874292/68228136-86147b80-ffba-11e9-9ef1-e543ada5b224.jpeg)
![WhatsApp Image 2019-11-05 at 9 34 52 AM](https://user-images.githubusercontent.com/2874292/68228138-86ad1200-ffba-11e9-925e-b37dbc961ba0.jpeg)

**Comment by sabas1080** [comment]
Christian ¿Las antenas usadas son a 915Mhz?

**Comment by christianacajabon** [comment]
Si correcto a 915Mhz

**Comment by wero1414** [comment]
No es nada comun que sean 20 cm incluso teniendo los transmisores sin antena solo con conector SMA (Cosa que no debes hacer), a mi me parece ser un problema de soldado del pin del RFM95 al conector de antena, habra que checar continuidad del pin de salida de RF a el pin interno del conector SMA

**Comment by wero1414** [comment]
Otra cosa, el pin DIO0 del radio esta conectado al pin 2 del Arduino uno para la interrupcion de recepcion de datos o bien el termino de transmisión, al ver las fotos creo que estas usando el pin 2 con un boton externo, por lo tanto puede que si tienes una configuración pull-down en tu boton puedes estar inyectando voltaje al pin DIO0 que puede estar haciendo que el radio funcione incorrectamente.

**Comment by christianacajabon** [comment]
Fijate que del ejemplo utilizado prescindi del siguiente codigo que dice que es opcional, ya que con este comando me daba un error de inicializar el Lora. Antes incluso de configurar botones, pantalla y modificar mis mensajes.

  // override the default CS, reset, and IRQ pins (optional)
  LoRa.setPins(csPin, resetPin, irqPin);// set CS, reset, IRQ pin

**Comment by wero1414** [comment]
Ese sirve por si usas el shield en otra tarjeta que no sea arduino uno, pero dejare el arduino uno por default

**Comment by christianacajabon** [comment]
Creo que si es un shield el problema, probe con un tercero y ya funciona bien. Como podria solucionar el problema del shield? O tiene alguna garantia?

**Comment by wero1414** [comment]
Para poder solucionarlo hay que ver que el pin de RF este bien soldado, te podemos ofrecer un descuento en futuras compras por las molestias en tu producto. 

![Captura de Pantalla 2019-11-05 a la(s) 13 36 23](https://user-images.githubusercontent.com/15166625/68239836-5886fc80-ffd1-11e9-8afc-46d424b8ea31.png)
